### ISSUE TITLE
Plugin not able to download via composer whenever there is new release

### ISSUE THREAD

**Issue by sandykadam** [onelogin/wordpress-saml#104]
Hi @pitbulk 

I think there is always issue when you release new code/tag. I use composer to download this plugin from "wppackagist", you recently released new code but I'm downloading previous version i.e 3.2.1 via composer and I get following error.

`    "wpackagist-plugin/onelogin-saml-sso":"3.2.1",`

```
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package wpackagist-plugin/onelogin-saml-sso could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by pitbulk** [comment]
Hi @sandykadam 

The plugin was marked as inactive by WP team due to an administrative issue, and that I believe made it unavailable at wpackagist.


Are you still experiencing such issue?

P.S The last official version was released in Apr ([3.2.1](https://github.com/onelogin/wordpress-saml/releases/tag/v3.2.1)) .
      I plan to release a new version soon.

**Comment by sandykadam** [comment]
Thanks @pitbulk Now its working fine, but I notice this issue last time as well when there was new release

**Comment by pitbulk** [comment]
wpackagist isn't an official packager maintained by WP.  I don't push data neither there, so no idea what could happen the other time.  This time I can provide the cause because it clear.
