### ISSUE TITLE
Suppressed PHP deprecation notice

### ISSUE THREAD

**Issue by tareiking** [onelogin/wordpress-saml#33]
When using [Query Monitor plugin](https://github.com/johnbillion/query-monitor) a suppressed notice is displayed in the event log as follows:

`add_contextual_help is deprecated since version 3.3.0! Use get_current_screen()->add_help_tab() instead.`

Relevant file is [here](https://github.com/onelogin/wordpress-saml/blob/master/onelogin-saml-sso/php/configuration.php#L49).

**Comment by pitbulk** [comment]
Can you provide a PR?
