### ISSUE TITLE
Non prefix SamlLogout

### ISSUE THREAD

**Issue by xsolon** [onelogin/wordpress-saml#42]
My Idp returns xml without prefixes. The xml is still valid since the namespaces are declared.

The logout process is returning: SLS endpoint found an error.logout_not_success

The following seems to be the problem (LogoutResponse.php line 94) for the xml below: 

`$entries = $this->_query('/samlp:LogoutResponse/samlp:Status/samlp:StatusCode');`

```
<LogoutResponse xmlns:samlp="urn:oasis:names:tc:saml:2.0:protocol" Destination="http://10.10.10.187/wp-login.php?saml_sls" ID="idb95d0f01f6cb4162909f8adc250c757e" InResponseTo="ONELOGIN_d53020fa00911a4035127612a86db7d981c0dd79" IssueInstant="2017-07-07T14:14:59.9824189Z" Version="2.0" xmlns="urn:oasis:names:tc:SAML:2.0:protocol">
   <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">MySts</Issuer>
   <Status>
   <StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
   </Status>
   </LogoutResponse>

```
Shouldn't this work? Seems to work for other SPs

Thanks

**Comment by pitbulk** [comment]
It should work, wordpress-saml uses internally php-saml as samltool.com does.

And if you try to validate the LogoutResponse at the [samltool validator](https://www.samltool.com/validate_logout_res.php), you will get a 
```
THE SAML LOGOUT RESPONSE IS VALID.
```

so you will need to review what is wrong on your environment.
