### ISSUE TITLE
Broken Travis Builds

### ISSUE THREAD

**Issue by tomjn** [onelogin/wordpress-saml#45]
Pull requests are showing failed tests as the travis builds are missing a `travis.yml`, triggering the default run which looks for a missing `rake` file

**Comment by pitbulk** [comment]
we not using travis for wordpress

**Comment by tomjn** [comment]
@pitbulk  That's a shame, does that mean if I made a pull request with a `travis.yml` that told Travis all builds passed, or did a PHP 7 syntax check, it wouldn't be merged?

**Comment by pitbulk** [comment]
if you want to contribute that, great
