### ISSUE TITLE
Improve the way multisite is supported

### ISSUE THREAD

**Issue by pitbulk** [onelogin/wordpress-saml#47]
Right now the SAML WP plugin works with multisites, but each site need to set its SAML settings.

We need to figure out how can be set a configuration on the network admin, and then let every site to use the settings set on network admin or use custom SAML settings, but is not implemented

**Comment by dnauck** [comment]
I would love to see this implemented, too. I can help testing.

**Comment by derekjhunt** [comment]
Another vote for this.

**Comment by alejandrobarrios07** [comment]
I think this PR is related with this issue.

https://github.com/onelogin/wordpress-saml/pull/78

**Comment by sandykadam** [comment]
Hey Guys,

Any update on this fix, we also looking for the same functionality in one of multisite project.

Thanks in advance.

**Comment by pitbulk** [comment]
3.1.0 supports multisite and added a way to clone settings
