### ISSUE TITLE
That ACS endpoint expects a SAMLResponse value sent using HTTP-POST binding. Nothing was found

### ISSUE THREAD

**Issue by vkapoor3141** [onelogin/wordpress-saml#58]
I may be doing something wrong in set up. I followed the [Onelogin instructions for setting this plugin up](https://support.onelogin.com/hc/en-us/articles/204353160-Configuring-SAML-for-WordPress)

and am hitting the error

`"That ACS endpoint expects a SAMLResponse value sent using HTTP-POST binding. Nothing was found"
`

when trying to hit the domain/wp-login.php?saml_acs endpoint. Turning on debug doesn't provide any further info. Please let me know what further info I can provide or if there's a better venue for solving this.

Thank you!

**Comment by pitbulk** [comment]
You can't access directly to domain/wp-login.php?saml_acs   that is an endpoint that expects a POST SAMLResponse from the IdP.

**Comment by vkapoor3141** [comment]
Many thanks, I'll resolve the issue.
