### ISSUE TITLE
Fix Notices: screen_icon and get_screen_icon deprecated

### ISSUE THREAD

**Issue by pitbulk** [onelogin/wordpress-saml#60]
At method onelogin_saml_configuration_render( )

Notice:  screen_icon is <strong>deprecated</strong> since version  3.8.0 with no alternative available. in  /var/www/onelogindemo/wordpress/wp-includes/functions.php on line 3842

Notice: get_screen_icon is <strong>deprecated</strong> since version 3.8.0 with no alternative available. in /var/www/onelogindemo/wordpress/wp-includes/functions.php on line 3842

**Comment by apeiron24** [comment]
Is that the way to fix it above or the exact question?

**Comment by pitbulk** [comment]
https://github.com/onelogin/wordpress-saml/commit/0fd954eb24c0ccd62e6a3a659a1780eb737c288a
