### ISSUE TITLE
Can't get roles to sync

### ISSUE THREAD

**Issue by adam-devapp** [onelogin/wordpress-saml#63]
I've followed the instructions here:
https://support.onelogin.com/hc/en-us/articles/204353160-Configuring-SAML-for-WordPress

and:
https://support.onelogin.com/hc/en-us/community/posts/115009793326-Mapping-Wordpress-Roles

However the roles do not sync across. I've applied the CN setting per Steve's post, and selected multiple roles (which there are).

Is there anything I have missed in the setup of role syncing with the free version of OneLogin?

**Comment by pitbulk** [comment]
Have you reviewed that the regex you added to the settings is correct?

Can you share your current settings and examples of the SAML Attributes?

**Comment by adam-devapp** [comment]
Create user if not exists TRUE
Update user data TRUE
Match Wordpress account by Username


Regular expression for multiple role values:
/CN=([^,;]*)/

Mappings:

![screen shot 2018-05-14 at 5 37 39 pm](https://user-images.githubusercontent.com/13082954/39985346-8d285728-579d-11e8-96c9-18db22523107.png)

Other:
![screen shot 2018-05-14 at 5 38 17 pm](https://user-images.githubusercontent.com/13082954/39985373-9b39336e-579d-11e8-8b8f-610c177b7e90.png)

**Comment by pitbulk** [comment]
What about the Attributes included on the SAMLResponse?

**Comment by adam-devapp** [comment]
![screen shot 2018-05-14 at 5 41 34 pm](https://user-images.githubusercontent.com/13082954/39985553-1e2efec0-579e-11e8-8603-ed2b499bd6cf.png)

I assuming you mean these mappings in OneLogin?

**Comment by adam-devapp** [comment]
I assume I would put a var_dump($var) and then exit() somewhere in the plugin code - Then attempt the login to dump this info?

**Comment by pitbulk** [comment]
I suggested you to use plugins that you install on browsers (SAML Tracer or Chrome SAML Panel) that are able to record the SAMLResponse.

But you can edit the functions.php file of the SAML plugin and print the $_POST['SAMLResponse'] on the acs method.

**Comment by adam-devapp** [comment]
Response is:
(Have changed name and email to xxx).

        <saml:Conditions NotBefore="2018-05-14T08:48:18Z" NotOnOrAfter="2018-05-14T08:54:18Z">
            <saml:AudienceRestriction>
                <saml:Audience>php-saml</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement AuthnInstant="2018-05-14T08:51:17Z"
            SessionIndex="xxx-3981-0136-790d-0a1b22056132" SessionNotOnOrAfter="2018-05-15T08:51:18Z">
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
            </saml:AuthnContext>
        </saml:AuthnStatement>
        <saml:AttributeStatement>
            <saml:Attribute Name="memberOf" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">administrators</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="User.email" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">xxx@xxx.com</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="User.FirstName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">xxx</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="User.LastName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">xxx</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="User.Username" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">xxx.xxx</saml:AttributeValue>
            </saml:Attribute>
        </saml:AttributeStatement>
    </saml:Assertion>

**Comment by pitbulk** [comment]
As you can see in the SAMLResponse, OneLogin is right now providing as member of the value "administrators" so no regex is required at all.

So remove the regular expression value, uncheck the "Multiple role values in one saml attribute value.

**Comment by adam-devapp** [comment]
Thanks. Works now. I had to set the memberOf value using rules, so it updates when the role is set. Otherwise it comes out blank in the debug log, even though the role is active (the memberOf remains blank without the rule).
