### ISSUE TITLE
Undefined variable $blog_id?

### ISSUE THREAD

**Issue by forevermatt** [onelogin/wordpress-saml#67]
It looks like the `$blog_id` variable used on **line 268** here hasn't been defined yet. Or am I missing something in the greater context?

https://github.com/onelogin/wordpress-saml/blob/d8690ff33aada4573198cdd633c9bbdbb1dfcba6/onelogin-saml-sso/php/functions.php#L267-L278

**Comment by pitbulk** [comment]
It seems you are right.

Do you have a PR?
