### ISSUE TITLE
Keycloak Integration 

### ISSUE THREAD

**Issue by tolstenko** [onelogin/wordpress-saml#71]
Hello!

I always get stuck in the url: /wp-login.php?saml_acs when redirected back from keycloak login. I keep receiving error 500 when returning the POST from IdP.

I am following the steps in "Wordpress SAML OneLogin plugin" from https://wiki.communecter.org/en/keycloak-_-configuration.html 

Here is the steps to reproduce the problem in our dev environment:
https://we.tl/PQRr9L7dZK

What can I do to make saml_acs work?

**Comment by pitbulk** [comment]
what error do you see at the logs?
