### ISSUE TITLE
Doesn't login for the first time.

### ISSUE THREAD

**Issue by prp20** [onelogin/wordpress-saml#72]
Hi,

Thanks for the plugin, it's very useful. But I have one problem while using this plugin. it doesn't login when you try it for the first time. We need to close the window twice or thrice and reopen it similar number of times to make it work. Please provide suitable suggestion on how to resolve this issue. Is there some configuration that i need to make on the WordPress code or is it issue with the SSO provider? need help urgently.

Thanks in advance.
Regards,

**Comment by donovandb** [comment]
Sounds to me like the problem is in the config of the SP or IDP, depending on your setup. I used this plugin and it works on first sign-in for me. What do you use for a service provider?

**Comment by pitbulk** [comment]
```I have one problem while using this plugin. it doesn't login when you try it for the first time. We need to close the window twice or thrice and reopen it similar number of times to make it work.```

Very strange that retrying, the error is gone and you can log.

Are you able to detail the issue you experience and review your logs.?
