### ISSUE TITLE
SLO URL 

### ISSUE THREAD

**Issue by sumitgupta911** [onelogin/wordpress-saml#75]
Hi,
I have installed plugin as a SP and unable to find a URL on plugin which will receive the Logout Response from my IDP. Like there is an ACS Url to consume Assertion, what is the Url to consume Logout response, and does it support POST.
Also how to set up SP private key in plugin, I have dumped it in certs folder but it doesn't work.
Thanks.
Sumit

**Comment by pitbulk** [comment]
You can see it on the metadata of your SP which link appears on the WP SAML settings configuration panel. Be sure you previously enabled Single Logout and saved the configuration with this parameter enabled.

**Comment by sumitgupta911** [comment]
Thanks for your prompt response Sixto. Though I was able to figure out the SLO link and able to successfully log out, but I am still having problems with setting Service Provider Key on the plugin. I am dumping the sp.key in the certs folder but it's unable to read the key. I have a pfx file which I renamed with .key extension and put it in certs folder. Please suggest.
Sumit

**Comment by sumitgupta911** [comment]
I have set up the key and certificate on the server. Hence closing
