### ISSUE TITLE
Signature not present in Authn Request

### ISSUE THREAD

**Issue by sumitgupta911** [onelogin/wordpress-saml#77]
Hi,
I have selected the option to Sign Auth request on the plugin and have dumped  key and crt in the certs folder. But the plugin is sending the Signature as a Query parameter and not signing the Authn Request. I believe Signature should be present in the Authn request. Please suggest.
Thanks,
Sumit

**Comment by pitbulk** [comment]
AuthNRequest is only supported with the HTTP-Redirect which Sign by Adding the Signature Query parameter, not embedding it on the XML

**Comment by sumitgupta911** [comment]
Okay, I will update my code accordingly then. Thanks :)
