### ISSUE TITLE
Getting Unable to extract public key on wp-login.php?saml_acs

### ISSUE THREAD

**Issue by alimohamed-moussa** [onelogin/wordpress-saml#79]
I'm trying to connect to my wordpress website with onelogin saml plugin.
When i click on "saml login" link, it goes back to my IDProvider login form. 

When i login, it works but it redirects me to my WordPress website (mysitedomain/wp-login.php?saml_acs) with this error " Unable to extract public key
There was at least one error processing the SAML Response: invalid_response
Contact the administrator ".

I use the SAML Tracer extension to inspect the request and the IDprovider response is success and i can see my access informations from the ID provider. But for some reasons i get an error on wp-login.phpsaml_acs part.

Can someone help? Please

**Comment by sandykadam** [comment]
This means the 509 key is different on your SAML WP configuration and the one on the SAML IDP provider. Key must be same on both end.

Another tip to login if you don't want the provider login is just just change the param `wp-login.php?normal` this will give you wordpress login screen.

**Comment by alimohamed-moussa** [comment]
Thany you
