### ISSUE TITLE
Keep seeing login page

### ISSUE THREAD

**Issue by bkno** [onelogin/wordpress-saml#80]
It seems some users get stuck in a cycle of logging in and getting redirected back to the login page endlessly. Has anyone else seen this?

The IDP is Salesforce in this case.

One user ran into this after logging in 14 hours after the account was set up.

I'm unable to replicate this so far but have seen the issue myself once when the the IDP login page won't go away.

**Comment by sandykadam** [comment]
Try to check in an incognito browser, for some reason, this has an issue with browser cache, I have also faced this issue.

**Comment by bkno** [comment]
@sandykadam thanks, I too found the login works when starting a private tab. This shows it's not an issue with the credentials. Did you see this with Salesforce or a different IDP? I'm trying to figure out where the problem lies.

**Comment by sandykadam** [comment]
We are using https://simplesamlphp.org/samlsp

**Comment by bkno** [comment]
Thanks @sandykadam. Makes me think it is a bug with this plugin or WordPress then.

As a workaround it seems using the IDP logout URL will let them log in successfully afterwards. I have Single Log Out setup. Only a workaround though, will try and debug more.

**Comment by sandykadam** [comment]
Yes, @bkno I also suspect it might be plugin or WordPress but maintainers can give more clarity on this. There is no specific use case to describe this behavior, sometimes it happens randomly on a different scenario.

**Comment by pitbulk** [comment]
I'm not aware of such bug.

Can you detail what are your SAML configuration, WP and SAML plugin versions?

**Comment by sandykadam** [comment]
WP - 5.2.3
SAML plugin - 3.0.0

**Comment by pitbulk** [comment]
I guess if only affected some users, then it could be related to the fact that the IdP data retrieved from those users where not enough to SSO or Just-in-time provision the user.
- Review data retrieved from Idp.
- Review attribute mappings.
- Review if there is some restriction with the user account if exists on WP (maybe deactivated)

**Comment by pitbulk** [comment]
See #73
