### ISSUE TITLE
fallback to WordPress user

### ISSUE THREAD

**Issue by solace** [onelogin/wordpress-saml#83]
Hi,

Once this plugin is configured, is it still possible to use a WordPress user to log in if ADFS is unavailable? We really only need a fallback available to log in as an admin user in the event the service is unavailable.

Thanks

**Comment by sandykadam** [comment]
@solace You need to log in using `wp-login.php?normal` this will give the default WP login screen.

**Comment by pitbulk** [comment]
@sandykadam gave you the trick
