### ISSUE TITLE
SSO update Overwrites Roles When IDp doesn't supply Roles

### ISSUE THREAD

**Issue by arkytn** [onelogin/wordpress-saml#86]
Latest version 3.1.0 with update user data. If the IDp does not supply roles, and you leave the Role mapping blank, SSO overwrites existing roles. This had the side effect of turning all my Administrators to Subscribers.!!

Need some way to disable update by attributes that are not mapped. Rolled back to 3.0.0

**Comment by pitbulk** [comment]
Try with the [3.1.1](https://github.com/onelogin/wordpress-saml/releases/tag/v3.1.1) version
