### ISSUE TITLE
Plugin is not able to download from https://wpackagist.org/ or wordpress plugin site

### ISSUE THREAD

**Issue by sandykadam** [onelogin/wordpress-saml#92]
We have build script using composer to download the plugins, but since Wordpress has blocked this plugin from downloading our builds failing.
Composer file we using `    "wpackagist-plugin/onelogin-saml-sso":"=3.1.1",`

`This plugin has been closed as of March 30, 2020 and is not available for download. This closure is temporary, pending a full review.`

**Comment by sandykadam** [comment]
@pitbulk any idea when this will get fixed?

**Comment by pitbulk** [comment]
Yes, we are aware of that and working on solving the issue.

**Comment by sandykadam** [comment]
Can close this issue since plugin is now available for download.
