### ISSUE TITLE
Error changing NameIDFormat in Advance Settings

### ISSUE THREAD

**Issue by egvinaspre** [onelogin/wordpress-saml#94]
Greetings!! Sorry for my poor english!! Thanks in advance. 

Wordpress 5.4 and 5.3.2
OneLogin SAML Plugin 3.1.1 (the latest version to which I can update the plugin)
Microsoft ADFS

The plugin has been working with nameID transient configuration for more than a year. 

But with the version 3.1.1, when i want to review the configuration, the nameID combo value is unspecified instead of transient and the website can not authenticate via SAML because of the following error: 

> That ACS endpoint expects a SAMLResponse value sent using HTTP-POST binding. Nothing was found 

I change the nameID combo to select transient again and i save the configuration, but when the config page is reloaded (after saving) the combo has the unspecified value again. 

I don't know what i'm doing wrong. Thanks for any help, if you need more information, please ask for it. 

Eduardo

**Comment by pitbulk** [comment]
It seems there is an error retrieving the value from the database to the form, but the value was stored properly in the database. I will fix this.
```
That ACS endpoint expects a SAMLResponse value sent using HTTP-POST binding. Nothing was found
```
This happens when you directly load the saml_acs endpoint not sending a $_POST['SAMLResponse']

**Comment by pitbulk** [comment]
Version 3.2.1 fixes this.

**Comment by egvinaspre** [comment]
Quick and easy!

Thank you very much!!!
