### ISSUE TITLE
Force SAML Login

### ISSUE THREAD

**Issue by ferhotguy** [onelogin/wordpress-saml#98]
After enabling force saml login feature, actual main URL also redirects back to OneLogin instance... How this is possible? Are they settings in WordPress or OneLogin that I am missing ?

Thanks

**Comment by ferhotguy** [comment]
example https://mydomain.com/wp-admin works fine with SAML onelogin, however after enabling force saml only option, https://mydomain.com also automatically redirects back to onelogin instance...

**Comment by pitbulk** [comment]
You are "Forcing SAML login", so if there is no session at WP, you are redirected to Onelogin in order to authenticate, and then a SAMLResponse is sent to WP SP ACS URL in order to process it, validate it and log the user.
